project_id = "nckzxwxxtyeydolmdijn"

[functions.whatsapp-instance-manager]
verify_jwt = false

[functions.whatsapp-message-sender]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.notify-new-lead]
verify_jwt = false

[functions.auto-first-message]
verify_jwt = false

[functions.whatsapp-global-instance-manager]
verify_jwt = false

[functions.meta-conversions-api]
verify_jwt = false

[functions.roleta-distribuir]
verify_jwt = false

[functions.roleta-timeout]
verify_jwt = false

[functions.notify-transfer]
verify_jwt = false