project_id = "rsbkcuyvnzpqqcbbaoqc"

[functions.whatsapp-instance-manager]
verify_jwt = false

[functions.whatsapp-global-instance-manager]
verify_jwt = false

[functions.create-broker-project]
verify_jwt = false

[functions.remove-broker-project]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.invite-member]
verify_jwt = false

[functions.create-invite]
verify_jwt = false

[functions.manage-seats]
verify_jwt = false

[functions.accept-invite]
verify_jwt = false

[functions.validate-invite]
verify_jwt = false

[functions.generate-landing-page]
verify_jwt = false

[functions.auto-cadencia-10d]
verify_jwt = false

[functions.auto-first-message]
verify_jwt = false

[functions.cancel-lead-cadencia]
verify_jwt = false

[functions.confirm-checkout]
verify_jwt = false
